version: '3.8'

services:
  server:
    build:
      context: ./backend
      dockerfile: Dockerfile
    volumes:
      - ./backend/:/backend/
    command: uvicorn app.api.server:app --reload --workers 1 --host 0.0.0.0 --port 8000
    env_file:
      - ./backend/.env
    ports:
      - "8000:8000"
    depends_on:
          - db
  db:
    image: postgres:16.2-alpine
    restart: always
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5
    volumes:
      - postgres_data:/var/lib/postgresql/data/
      - ./backend/app/db/init.sql:/docker-entrypoint-initdb.d/create_tables.sql
    env_file:
      - ./backend/.env
    ports:
      - "50000:5432"

volumes:
    postgres_data: